# This workflow will build a Java project with Maven, run tests, generate code coverage reports using JaCoCo, and upload the reports to Codecov.
# For more information, see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: LeetCode Build and Test with JaCoCo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Clean, test, and generate JaCoCo reports with Maven
      run: mvn clean test jacoco:report --file pom.xml
    - name: Upload JaCoCo coverage report
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}  # Set this in your GitHub repository secrets
